apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: ExternalName
  externalName: petclinic.csnse4y8u9br.us-east-1.rds.amazonaws.com
